language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base portaudio19-dev libsndfile-dev libsamplerate-dev
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc 
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - cp ../desktop/eko.desktop .
  - cp ../icons/eko.png .
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/eko -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/eko -appimage 
  - curl --upload-file ./EKO*.AppImage https://transfer.sh/EKO-git.$(git rev-parse --short HEAD)-x86_64.AppImage 
